# Generated by Django 3.2.15 on 2024-07-27 20:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lapor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pelapor', models.CharField(max_length=100)),
                ('nik', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=254)),
                ('nohp', models.CharField(max_length=15)),
                ('jenis_pelaporan', models.CharField(choices=[('Jalan Lingkungan', 'Jalan Lingkungan'), ('Drainase Lingkungan', 'Drainase Lingkungan'), ('Rumah Tidak Layak Huni (RTLH)', 'Rumah Tidak Layak Huni (RTLH)')], max_length=50)),
                ('lokasi', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('kondisi', models.TextField()),
                ('status', models.CharField(choices=[('Baru_Masuk', 'Baru Masuk'), ('Diterima', 'Diterima'), ('Ditolak', 'Ditolak'), ('Diproses', 'Diproses'), ('Selesai', 'Selesai')], default='Baru_Masuk', max_length=15)),
                ('tanggal_pelaporan', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='photos/')),
                ('lapor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='report.lapor')),
            ],
        ),
    ]
