# Generated by Django 3.2.15 on 2024-07-27 21:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lapor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='lapor',
            name='kondisi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lapor',
            name='lokasi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lapor',
            name='status',
            field=models.CharField(blank=True, choices=[('Baru_Masuk', 'Baru Masuk'), ('Diterima', 'Diterima'), ('Ditolak', 'Ditolak'), ('Diproses', 'Diproses'), ('Selesai', 'Selesai')], default='Baru_Masuk', max_length=15),
        ),
        migrations.AlterField(
            model_name='lapor',
            name='tanggal_pelaporan',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
