# Generated by Django 3.2.15 on 2024-07-27 23:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_auto_20240728_0450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lapor',
            name='status',
            field=models.CharField(choices=[('Baru_Masuk', 'Baru Masuk'), ('Diterima', 'Diterima'), ('Ditolak', 'Ditolak'), ('Diproses', 'Diproses'), ('Selesai', 'Selesai')], default='Baru_Masuk', max_length=15),
        ),
        migrations.AlterField(
            model_name='lapor',
            name='tanggal_pelaporan',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
