# Generated by Django 3.2.15 on 2024-07-27 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_auto_20240728_0620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lapor',
            name='jenis_pelaporan',
            field=models.CharField(choices=[('Jalan Lingkungan', 'Jalan Lingkungan'), ('Drainase Lingkungan', 'Drainase Lingkungan'), ('RTLH', 'Rumah Tidak Layak Huni (RTLH)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='lapor',
            name='kondisi',
            field=models.TextField(default=''),
        ),
    ]
